package com.callNest.app.domain.model

import java.util.Calendar

/**
 * Lead temperature bucket derived from `ContactMetaEntity.computedLeadScore`.
 *
 * The thresholds (Cold < 34, Warm 34..66, Hot > 66) intentionally mirror the
 * sliders in Sprint 6's lead-scoring settings so users have a consistent
 * mental model across the app.
 */
enum class LeadBucket { Cold, Warm, Hot }

/**
 * Severity for an [Insight]. Drives the border color in the Stats UI.
 */
enum class Severity { Info, Warn, Critical }

/**
 * Inclusive `[from, to]` epoch-millis time window used by every stats query.
 *
 * The companion presets all anchor to the device's local-time `Calendar`
 * "today" so a user sliding through presets sees stable boundaries even
 * across DST transitions.
 */
data class DateRange(val from: Long, val to: Long) {
    companion object {
        private fun startOfDay(cal: Calendar): Long {
            cal.set(Calendar.HOUR_OF_DAY, 0)
            cal.set(Calendar.MINUTE, 0)
            cal.set(Calendar.SECOND, 0)
            cal.set(Calendar.MILLISECOND, 0)
            return cal.timeInMillis
        }

        fun today(): DateRange {
            val from = startOfDay(Calendar.getInstance())
            return DateRange(from, from + 86_400_000L - 1)
        }

        fun last7Days(): DateRange {
            val to = System.currentTimeMillis()
            val cal = Calendar.getInstance().apply { add(Calendar.DAY_OF_YEAR, -6) }
            return DateRange(startOfDay(cal), to)
        }

        fun last30Days(): DateRange {
            val to = System.currentTimeMillis()
            val cal = Calendar.getInstance().apply { add(Calendar.DAY_OF_YEAR, -29) }
            return DateRange(startOfDay(cal), to)
        }

        fun thisMonth(): DateRange {
            val cal = Calendar.getInstance().apply { set(Calendar.DAY_OF_MONTH, 1) }
            return DateRange(startOfDay(cal), System.currentTimeMillis())
        }

        fun lastMonth(): DateRange {
            val cal = Calendar.getInstance().apply {
                add(Calendar.MONTH, -1)
                set(Calendar.DAY_OF_MONTH, 1)
            }
            val from = startOfDay(cal)
            cal.add(Calendar.MONTH, 1)
            val to = startOfDay(cal) - 1
            return DateRange(from, to)
        }

        fun last90Days(): DateRange {
            val to = System.currentTimeMillis()
            val cal = Calendar.getInstance().apply { add(Calendar.DAY_OF_YEAR, -89) }
            return DateRange(startOfDay(cal), to)
        }
    }
}

/** Aggregate counters rendered in the Stats overview row. */
data class OverviewMetrics(
    val totalCalls: Int,
    val totalTalkTimeSec: Long,
    val avgDurationSec: Int,
    val missedRate: Double,
    val unsavedRate: Double,
    val leadDistribution: Map<LeadBucket, Int>
)

/** A single point on a daily-trend line chart. */
data class TrendPoint(val label: String, val value: Double, val ts: Long)

/** A donut slice for the call-type breakdown chart. */
data class CallTypeSlice(val label: String, val count: Int, val color: Long)

/** One cell of the 24x7 day-of-week × hour heatmap. */
data class HourlyHeatmapCell(val dayOfWeek: Int, val hour: Int, val count: Int)

/** A row in the Top Numbers leaderboard. */
data class LeaderboardEntry(
    val normalizedNumber: String,
    val displayName: String?,
    val callCount: Int,
    val totalDurationSec: Long
)

/** A user-facing recommendation generated by `GenerateInsightsUseCase`. */
data class Insight(val text: String, val severity: Severity)

/** Snapshot returned by `ComputeStatsUseCase` for a [DateRange]. */
data class StatsSnapshot(
    val range: DateRange,
    val overview: OverviewMetrics,
    val dailyVolume: List<TrendPoint>,
    val dailyMovingAverage: List<TrendPoint>,
    val callTypes: List<CallTypeSlice>,
    val heatmap: List<HourlyHeatmapCell>,
    val topByCount: List<LeaderboardEntry>,
    val insights: List<Insight>
)
